/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:28dfb0dd-337c-4cfc-b5d7-8cd7efae3ec1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_CUHLWLNGV",
    "aws_user_pools_web_client_id": "4gn6ir9519hec14k90pt0aso28",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://cnlsib3uujfglot4cwv2jczomi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "trial2102749-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
